### ISSUE TITLE
Official adapter

### ISSUE THREAD

**Issue by balazsorban44** [michalsvorc/next-auth-dynamodb-adapter#1]
Hi there, just a heads up, we now have an official `@next-auth/dynamodb-adapter`!

Here is the source code: https://github.com/nextauthjs/adapters/tree/canary/packages/dynamodb

If you are interested in contributing/maintaining, we welcome you there! :hugs:

**Comment by michalsvorc** [comment]
Hi, thanks for the info, I've provided a link in the README file.

Commit: [1c04ff244206f3b8b419af9e8f290e90620a7d2e](https://github.com/michalsvorc/next-auth-dynamodb-adapter/commit/1c04ff244206f3b8b419af9e8f290e90620a7d2e)

**Comment by balazsorban44** [comment]
So If I have to guess you either have custom requirements that force you to use a non-official version or simply want an adapter with full control over the source code?

If you are interested, we would like you very much to help out with the official adapter, in case you have ideas on how to improve it! :slightly_smiling_face:

In any case, I do not want to push anything, and I accept if you are not interested, but feel free to contact me, if you have any questions!

Have a nice day! :slightly_smiling_face:

**Comment by michalsvorc** [comment]
No, I just didn't test the official version yet, so I've only updated the README for now to let people know that the official adapter is available. I'll keep my repository up for people that might already be using it or if I need to implement some custom features in the future. I also like TypeScript source code in and AWS SDK v3 for DynamoDB client.

Thanks, when I'll be testing the official adapter I'll let you know there will be any ideas for improvement.

Have a nice day too.
